### ISSUE TITLE
💡 [REQUEST] - refactor ttp directory structure

### ISSUE THREAD

**Issue by VVX7** [facebookincubator/ForgeArmory#33]
### Summary

TTPs should follow a regular directory structure. Using a regular directory structure to organize TTPs makes it easier for users to navigate and therefore an overall more accessible tool. 

### Basic Example

I suggest roughly following MITRE matrices so that the directory structure looks like <OS/Tactic/Technique/Sub-Technique/procedure>. I've used the tactic/technique names because it's more accessible than tactic/techniques IDs when skimming content.

<img width="787" alt="CleanShot 2023-08-21 at 13 27 05@2x" src="https://github.com/facebookincubator/ForgeArmory/assets/46228229/9c964347-e216-4159-a04a-53be20673d27">

### Drawbacks

Drawback: not everything fits in mitre attack so there are always oddballs; procedures may fits in multiple tactics/techniques so placing them is often a case of 'best fit' or preference.

Impact: renaming everything

**Comment by VVX7** [comment]
Looking at https://github.com/facebookincubator/TTPForge/issues/196 and seeing you plan to support multiple os/arch in each ttp so the top level OS dir wouldn't be necessary but the rest still tracks.

**Comment by l50** [comment]
Thanks for the issue! The drawback you mentioned is a big part of why we haven't 100% aligned with MITRE ATT&CK. We've run a lot of TTPs that do not have proper representation in MITRE ATT&CK. Once you get into daisy-chaining, the translation becomes even more challenging.

In terms of the layout for TTPs, I wanted to try and have it to be as intuitive as possible to find and run a TTP, while minimizing avenues for duplication. For example, you can have a TTP that works for macOS, and linux (like the one you submitted, thanks again!). If we group by OS, then we end up with duplicate TTPs or have to do something like a symlink, which I don't love. 

In an ideal world, I'd love to find a happy medium between the intuitive layout of [nuclei-templates](https://github.com/projectdiscovery/nuclei-templates) and the deduplication of modules that [msf](https://github.com/rapid7/metasploit-framework/tree/master/modules) has achieved.

**Comment by VVX7** [comment]
Guessing a daisy-chain is like a playbook of atomic operations? I see how those won't fit MITRE ATT&CK, nor will most atomic operations such as file read/write and all the other boilerplate you might want to put in a standard library for writing ttps.

Something like msf's categories might work in a standard library, where it makes sense to organize operations by how each interacts with the operating system, such as filesystem, process, native API operations.

Might be time to add a search feature to TTPForge so you can filter by MITRE ATT&CK tactic/technique, custom tags, or pattern matching the readme, for example. It doesn't solve what the directory structure should look like but may make it easier for folks to find what they're looking for on their own terms.

**Comment by l50** [comment]
> Guessing a daisy-chain is like a playbook of atomic operations?

Yep! 



> I see how those won't fit MITRE ATT&CK, nor will most atomic operations such as file read/write and all the other boilerplate you might want to put in a standard library for writing ttps.

Yeah, it's a tricky bit of business. Figure (like ansible) if we've got singleton entities and we continue to build out the forge with daisy-chain support in mind, we should be able to find a happy medium.



> Something like msf's categories might work in a standard library, where it makes sense to organize operations by how each interacts with the operating system, such as filesystem, process, native API operations.

Agreed. I like what they did with the exception of the lack of intuitiveness when it comes to finding the module you're looking for - that part could be better.



> Might be time to add a search feature to TTPForge so you can filter by MITRE ATT&CK tactic/technique, custom tags, or pattern matching the readme, for example. It doesn't solve what the directory structure should look like but may make it easier for folks to find what they're looking for on their own terms.

I think we have something in place already that @d3sch41n added, but he'll know better than I :)

**Comment by l50** [comment]
We've restructured the TTP layout in #48, closing.
